#File name: ci.yml
#Author: Kyle McColgan
#Date: 1 October 2026
#Description: This file contains the GitHub Actions Workflow and GitHub Pages deployment processes for the Countdown React project.

name: CI and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write  # For push to the gh-pages branch...

#Prevents multiple concurrent deployments from stepping on each other...
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v7

    - name: Set up Node.js
      uses: actions/setup-node@v7
      with:
        node-version: '24'

    - name: Install dependencies
      run: npm install

    - name: Build the site
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages           # The branch to push to.
        folder: dist               # Vite's build folder is dist.
        token: ${{ secrets.GH_TOKEN }}  # Using the PAT secret for deployment.
